BTMS/BTMS.Web/ViewModels/BusDataViewModel.cs
using BTMS.BlazorApp.Shared.Models;

namespace BTMS.Web.ViewModels
{
    public class BusDataViewModel
    {
        public int BusId {  get; set; }
        public int BusRouteId {  get; set; }
        public BusType BusType { get; set; }
        public decimal Fare {  get; set; }  
        public int SeatCount {  get; set; }

        public List<Booking> Bookings { get; set; }= new List<Booking>();
    }
}

BTMS/BTMS.Web/ViewModels/SearchResultViewModel.cs
using BTMS.BlazorApp.Shared.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BTMS.Web.ViewModels
{
    public class SearchResultViewModel
    {
        public int BusId { get; set; }
        [Required, StringLength(50)]
        public string Name { get; set; } = default!;
        [Required, StringLength(50)]
        public string Number { get; set; } = default!;
        [Required, EnumDataType(typeof(BusType))]
        public BusType BusType { get; set; }
        [Required]
        public int? Capacity { get; set; }
        [Required, StringLength(120)]
        public int BusRouteId { get; set; }


        [Required, StringLength(100)]
        public string From { get; set; } = default!;//From

        [Required, StringLength(80)]
        public string To { get; set; } = default!;//To
        public decimal Fare { get; set; }
        public int BusScheduleId { get; set; }
        [Required, Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [Required, Column(TypeName = "time")]
        public TimeSpan? Time { get; set; }
        

    }
}

BTMS/BTMS.Web/ViewModels/SearchViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BTMS.Web.ViewModels
{
    public class SearchViewModel
    {
        [Required]
        public string From { get; set; } = default!;
        [Required]
        public string To { get; set; } = default!;
        [Required]
        public DateTime? Date { get; set; }
    }
}

BTMS/BTMS.Web/Controllers/BookingsController.cs
using BTMS.BlazorApp.Shared.Models;
using BTMS.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;
namespace BTMS.Web.Controllers
{
    public class BookingsController : Controller
    {
        private readonly BusDbContext db;
        public BookingsController(BusDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Search(SearchViewModel data)
        {
            var routeId = db.BusRoutes.FirstOrDefault(x=> x.From == data.From &&  x.To == data.To)?.BusRouteId;
            if(routeId == null)
            {
                return NotFound();
            }
            List<BusSchedule> busSchedules = db.Schedules                   
                  
                   .Where(x=> x.BusRouteId == routeId).ToList();
            if(data.Date?.Date == DateTime.Today)

            {
                  busSchedules = busSchedules
                    
                    .Where(x=> (x.Date == DateTime.Today && x.Time > (DateTime.Today - DateTime.Now)))
                   .ToList();
                
            }
            else
            {


                 busSchedules = busSchedules
               
                    .Where(x =>x.Date == data.Date)
                   .ToList();
                
            }
           
            var modelData=busSchedules.Select(sch =>            
            new SearchResultViewModel
            {
                BusScheduleId = sch.BusScheduleId,
                BusId = sch.BusId,
                BusType = GetType(sch.BusId),
                BusRouteId = routeId.Value,
                From = GetFrom(routeId.Value),
                To = GetTo(routeId.Value),
                Date = sch.Date,
                Time = sch.Time,
                Name = sch.Bus == null ? "" : sch.Bus.Name,
                Capacity = sch.Bus == null ? 0 : sch.Bus.Capacity,
                Fare = GetFare(sch.BusRouteId, sch.BusId)
                
            }).ToList();
            return View(modelData);
        }
        public IActionResult BookSeats(int id, int busId)
      {
            var b = db.Buses.FirstOrDefault(x => x.BusId == busId);
            if (b == null) return NotFound();
            var sch = db.Schedules.FirstOrDefault(x=> x.BusScheduleId == id);
            if (sch == null) return NotFound();
            var data = new BusDataViewModel { BusId = busId, BusRouteId = id, BusType = b.BusType, SeatCount = b.Capacity == null ? 0: b.Capacity.Value };
           data.Bookings= db.Bookings.Where(x => x.ScheduleId == id).ToList();

            if(b.BusType == BusType.Sleeper || b.BusType == BusType.DoubleDecker)
            {
                var labels = Enumerable.Range((int)'A', data.SeatCount / 8).Select(x => (char)x).ToList();
                ViewBag.Labels = labels;
                return View("DoubleLayerBus", data);
            }
            else
            {
                var labels = Enumerable.Range((int)'A', data.SeatCount / 4).Select(x => (char)x).ToList();
                ViewBag.Labels=labels;
                
                return View("SingleLayerBus", data);
            }
            
        }
        public JsonResult GetDestination(string from)
        {
            var data = db.BusRoutes.Where(x=> x.From == from).Select(x=> x.To).ToList();
            return Json(data);
        }
        private decimal GetFare(int routeId, int busId)
        {
           var bus = db.Buses.First(x=> x.BusId == busId);
            var Fare = db.Fares.Where(x => x.BusType == bus.BusType && x.BusRouteId == routeId && x.IsActive).FirstOrDefault();
            return Fare == null ?  0 : Fare.SeatFare;
        }
        private string GetFrom(int RouteId)
        {
            
            var From = db.BusRoutes.First(x => x.BusRouteId== RouteId).From;
            return From;
        }
        private string GetTo(int RouteId)
        {

            var To = db.BusRoutes.First(x => x.BusRouteId == RouteId).To;
            return To;
        }
        private BusType GetType(int busId)
        {
            var t = db.Buses.First(x => x.BusId == busId).BusType;
            return t;
        }
    }
}

BTMS/BTMS.Web/Controllers/HomeController.cs
using BTMS.BlazorApp.Shared.Models;
using Microsoft.AspNetCore.Mvc;

namespace BTMS.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly BusDbContext db;
        public HomeController(BusDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            ViewBag.FromList = db.BusRoutes.Select(r=> r.From).Distinct().ToList();
            return View();
        }
    }
}

BTMS/BTMS.Web/Views/Bookings/DoubleLayerBus.cshtml
@{
    ViewData["Title"] = "Double";
}

<h1>Double</h1>

BTMS/BTMS.Web/Views/Bookings/Search.cshtml
@model IEnumerable<SearchResultViewModel>
@using BTMS.BlazorApp.Shared.Models
@{
    ViewData["Title"] = "Search";
}

<div class="row">
    <div class="col-12">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Route
                    </th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Bus Type</th>
                    <th>Fare</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@x.From - @x.To</td>
                        <td>@x.Date?.ToString("yyyy-MM-dd")</td>
                        <td>@(DateTime.Today.Add(x.Time.Value).ToString("hh:mm tt"))</td>
                        <td>@((BusType)x.BusType)</td>
                        <td>@x.Fare.ToString("0.00")</td>
                        <td>
                            <a class="btn btn-success btn-sm" asp-controller="Bookings" asp-action="BookSeats" asp-route-id="@x.BusScheduleId" asp-route-busid="@x.BusId">Book</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BTMS/BTMS.Web/Views/Bookings/SingleLayerBus.cshtml
@model BusDataViewModel
@{
    ViewData["Title"] = "SingleLayerBus";
}


<div class="row">
    <div class="col-8">
        <div style="width: 252px;margin:0 auto;" class="border-1">
            <div class="diver-layout">
                <div></div>
                <div class="driver"></div>
            </div>
            <div class="bus-layout">
                @for (var i = 0; i < ViewBag.Labels.Count; i++)
                {

                    for (var j = 1; j <= 4; j++)
                    {
                     
                            if (Model.Bookings.Any(x => x.SeatNumber == ViewBag.Labels[i].ToString() + j))
                            {
                            <span class="seat" id="@(ViewBag.Labels[i].ToString() + j)" data-status="sold" data-seat="@(ViewBag.Labels[i].ToString() + j)">
                                <i class="bi bi-check-all"></i>
                            </span>
                            }
                            else
                            {
                            <span id="@(ViewBag.Labels[i].ToString() + j)" class="seat" data-status="free" data-seat="@(ViewBag.Labels[i].ToString() + j)">
                                @(ViewBag.Labels[i].ToString() + j)
                                </span>
                            }

                       
                        if (j == 2)
                        {
                            <span></span>
                        }
                    }
                }
            </div>
        </div>
    </div>
</div>
@section styles {
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        .bus-layout
        {
            display:grid;
            width:250px;
            grid-template-columns: 50px 50px 50px 50px 50px;
            grid-column-gap: 5px;
            grid-row-gap:3px;
           
            
        }
        .seat {
            /*background: url('/Images/seat.png') no-repeat;*/
            display:flex;
            width: 48px;
            height: 48px;
            border: 1px solid #ccc;
            background-size: contain;
            align-items:center;
            align-items:center;
            border-radius:.25rem;
            justify-content:center;
            justify-items:center;
            text-align:center;
            cursor:pointer;
        }

        .diver-layout{
            display: grid;
            width:250px;
            grid-template-columns: 200px 50px;
            grid-column-gap: 2px;
            margin-bottom: 3px;
        }
        .driver
        {
            background: url('/Images/driver.png') no-repeat;
            display: flex;
            width: 48px;
            height: 48px;
            border: 1px solid #ccc;
            background-size: contain;
            align-items: center;
            align-items: center;
            border-radius: .25rem;
            justify-content: center;
            justify-items: center;
            text-align: center;
        }
    </style>
}
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script>
        $(".seat").click(function(){
            let id = $(this).data("seat");
            let status=$(`#${id}`).data('status');
            console.log(status)
            if (status == "sold") return;
            else if (status == "free") {
                $(`#${id}`).data('status', 'selected');
                $(`#${id}`).html(`<i class='bi bi-check2'></i>`)
            }
            else {
                $(`#${id}`).data('status', 'free');
                $(`#${id}`).text(id);
            }
        })
    </script>
}

BTMS/BTMS.Web/Views/Home/Index.cshtml
@model SearchViewModel
@{
    ViewData["Title"] = "Index";
}


<div class="row">
    <div class="col-12">
        <h3>Search Buses</h3>
        <form asp-action="Search" asp-controller="Bookings" method="post">
            <div class="form-group row mb-1">
                <div class="col-3">
                    <select asp-for="From" asp-items="@(new SelectList(ViewBag.FromList))" class="form-select form-select-sm">
                        <option value="" selected>From</option>
                        <span  asp-validation-for="From"></span>
                    </select>
                </div>
                <div class="col-3">
                    <select asp-for="To" class="form-select form-select-sm">
                        <option value="" selected>Destination</option>
                    </select>
                    <span asp-validation-for="To"></span>
                </div>
                <div class="col-3">
                    <input type="text" asp-for="Date" placeholder="Travel date" class="form-control form-control-sm" />
                    <span asp-validation-for="To"></span>
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-primary btn-sm">Search</button>

                </div>
            </div>
        </form>
    </div>
</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="~/libs/datepicker/css/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts
{
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/validate/jquery.validate.unobtrusive.js"></script>
    <script src="~/libs/datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        $("#Date").datepicker({
            format: "yyyy-mm-dd"
        });
        $("#From").change(function () {
            var from = $(this).val();
            $.ajax({
                type:"get",
                url: "/Bookings/GetDestination?from="+from,
                success: r => {
                    console.log(r);
                    $("#To").empty();
                    for (var i = 0; i < r.length; i++) {
                        $("#To").append(`<option>${r[i]}</option>`)
                    }
                    $("#To").append(`<option value="" selected>Destination</option>`)

                }
            })
        })
    </script>
}

BTMS/BTMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/libs/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/libs/bootstrap/js/bootstrap.bundle.js"></script>
  

   
    <style>
        body{
            padding-top:70px;
        }
    </style>
    @await RenderSectionAsync("styles", false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm fixed-top">
        <div class="container-fluid">
            <span class="navbar-brand">BTMS Go Ticket</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <footer class="container-fluid">
        @DateTime.Today.Year BTMS
    </footer>
    @await RenderSectionAsync("scripts", false)
</body>
</html>